drop table if exists compilation_event;
drop table if exists compilations;
drop table if exists requests;
drop table if exists events;
drop table if exists locations;
drop table if exists categories;
drop table if exists users;

create table if not exists users
(
    id    bigint generated by default as identity not null,
    name  varchar(255)                            not null,
    email varchar(255)                            not null,
    constraint pk_user
        primary key (id),
    constraint un_user_email unique (email)
);

create table if not exists categories
(
    id      bigint generated by default as identity not null,
    name    varchar(255)                            not null,
    constraint pk_category
        primary key (id),
    constraint un_category_name unique (name)
);

create table if not exists locations
(
    id        bigint generated by default as identity not null,
    latitude  double precision                        not null,
    longitude double precision                        not null,
    constraint pk_location
        primary key (id),
    constraint un_location unique (latitude, longitude)
);

create table if not exists events
(
    id                    bigint generated by default as identity not null,
    title                 varchar(255)                            not null,
    annotation            varchar(4000)                           not null,
    description           varchar(4000)                           not null,
    is_paid               boolean                                 not null,
    event_date            timestamp without time zone             not null,
    user_id               bigint                                  not null,
    category_id           bigint                                  /*not null*/,
    location_id           bigint                                  not null,
    participant_limit     bigint                                  not null,
    is_request_moderation boolean                                 not null,
    created_on            timestamp without time zone             not null,
    published_on          timestamp without time zone             not null,
    state                 varchar(255)                            not null,
    constraint pk_event
        primary key (id),
    constraint fk_event_user_id
        foreign key (user_id) references users (id),
    constraint fk_event_location_id
        foreign key (location_id) references locations (id),
    constraint fk_event_category_id
        foreign key (category_id) references categories (id)
);

create table if not exists requests
(
    id       bigint generated by default as identity not null,
    event_id bigint                                  not null,
    user_id  bigint                                  not null,
    status   varchar(50)                             not null,
    created  timestamp without time zone             not null,
    constraint pk_user_request
        primary key (id),
    constraint fk_user_request_user_id
        foreign key (user_id) references users (id),
    constraint fk_user_request_event_id
        foreign key (event_id) references events (id)
);

create table if not exists compilations
(
    id        bigint generated by default as identity not null,
    title     varchar(255)                            not null,
    is_pinned boolean                                 not null,
    constraint pk_compilation
        primary key (id)
);

create table if not exists compilation_event
(
    id             bigint generated by default as identity not null,
    compilation_id bigint                                  not null,
    event_id       bigint                                  not null,
    constraint pk_compilation_event
        primary key (id),
    constraint fk_compilation_event_compilation_id
        foreign key (compilation_id) references compilations (id),
    constraint fk_compilation_event_event_id
        foreign key (event_id) references events (id)
);