version: '3.1'
services:
  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - MAIN_SERVICE_DB_URL=jdbc:postgresql://main-db:5432/main-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_SERVICE_DB_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin