drop table if exists stats;

create table if not exists stats
(
    id        bigint generated by default as identity not null,
    app       varchar                                 not null,
    uri       varchar                                 not null,
    ip        varchar                                 not null,
    timestamp timestamp without time zone             not null,
    constraint pk_stats
        primary key (id)
);
